// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw1g-DlCPnmDmiq3FwiRdHKJ7PRU1iGcA',
    appId: '1:922815238113:web:002f0cd047f129a2ddcca0',
    messagingSenderId: '922815238113',
    projectId: 'task-manager-25cb6',
    authDomain: 'task-manager-25cb6.firebaseapp.com',
    storageBucket: 'task-manager-25cb6.firebasestorage.app',
    measurementId: 'G-S44B0EWSW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4UxKGT8_t2eqPq5W3BaZVwwGkHzcf65A',
    appId: '1:922815238113:android:919675bc0dd86c3dddcca0',
    messagingSenderId: '922815238113',
    projectId: 'task-manager-25cb6',
    storageBucket: 'task-manager-25cb6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnYAlMeL9kPoH1yYdgl9hkHpyip_xmQpg',
    appId: '1:922815238113:ios:0b70c2b13c52059fddcca0',
    messagingSenderId: '922815238113',
    projectId: 'task-manager-25cb6',
    storageBucket: 'task-manager-25cb6.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnYAlMeL9kPoH1yYdgl9hkHpyip_xmQpg',
    appId: '1:922815238113:ios:0b70c2b13c52059fddcca0',
    messagingSenderId: '922815238113',
    projectId: 'task-manager-25cb6',
    storageBucket: 'task-manager-25cb6.firebasestorage.app',
    iosBundleId: 'com.example.taskManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw1g-DlCPnmDmiq3FwiRdHKJ7PRU1iGcA',
    appId: '1:922815238113:web:a3ea5c03e2b91e16ddcca0',
    messagingSenderId: '922815238113',
    projectId: 'task-manager-25cb6',
    authDomain: 'task-manager-25cb6.firebaseapp.com',
    storageBucket: 'task-manager-25cb6.firebasestorage.app',
    measurementId: 'G-DB0VEHWKEV',
  );
}
